public class OrderOfExecuition {
/*
1)Fetch Data
2)Validation Rules 
	a) System Validations
	b) Custom Validations  ammount > 10000 error    5000
3)Before Triggers
4) validations 
4)Duplicate Rules
5)Saves the record
6)After Triggers
7)Assignment Rules
8)Auto Responsive rules
9)Work Flow rules
    --> If any field Update occurs then the execuition again starts from step 3   
10)Flows and Process Builder  --- ammount =20000
11)Escsalation Rules
12)Entiltment Rules
13)Rollup Summary Fileds
14)Parent Record Updates
15)Criteria based sharing rules
16)Commits record to data base
17)Send Emails and any other post data logics.











*/

}